import type { Metadata } from 'next'
import Link from 'next/link'
import { ReactNode } from 'react'

import ReadList from '@/components/ReadList'
import './globals.css'

export const metadata: Metadata = {
  title: 'Web Tutorial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="p-8">
        <h1 className="uppercase text-5xl mb-8">
          <Link href="/">web</Link>
        </h1>
        <ol className="mb-6">
          <ReadList />
        </ol>
        {children}
        <ul className="capitalize">
          <li>
            <Link href="/create" className="underline">
              create
            </Link>
          </li>
          <li>
            <Link href="/update/1" className="underline">
              update
            </Link>
          </li>
          <li className="underline">
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  )
}
